# Generated by Django 3.0.4 on 2020-05-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200515_1516'),
        ('genders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='books',
            field=models.ManyToManyField(related_name='books', to='books.Book'),
        ),
    ]
