# Generated by Django 3.0.4 on 2020-05-15 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('genders', '0002_auto_20200515_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genders.Gender')),
            ],
        ),
    ]
