# Generated by Django 3.0.4 on 2020-05-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('genders', '0003_authorgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='auhthors',
            field=models.ManyToManyField(through='genders.AuthorGender', to='authors.Author'),
        ),
    ]
